### ISSUE TITLE
Optimization without equality constraints

### ISSUE THREAD

**Issue by jokla** [liuq/QuadProgpp#3]
Hi!

What am I supposed to do if I don't have any equality constraints in my optimization problem?
How should define CE and ce0?

Thanks!

**Comment by liuq** [comment]
Hi Giovanni,

unfortunately I didn’t take care of such an optimisation in the code. But,
I guess that you can simply define a single column matrix with zero values
and put ce0 to the singleton 0 and it should work.

All the best,

Luca

On 31 luglio 2017 a 11:07:51, Giovanni Claudio (notifications@github.com)
scritto:

Hi!

What am I supposed to do if I don't have any equality constraints in my
optimization problem?
How should define CE and ce0?

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/liuq/QuadProgpp/issues/3>, or mute the thread

**Comment by jokla** [comment]
Hi liuq,

Thanks for your prompt response! In fact, I tried using zero values but I got the following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Constraints are linearly dependent
```
Then I tried using very small numbers and I don't get that error. I guess it should be OK!

Giovanni

**Comment by jokla** [comment]
It is working. Thanks for the help!

**Comment by aghaeifar** [comment]
> It is working. Thanks for the help!

@jokla , 
How did you make it to work finally? I also get runtime error when CE is set to zero.
